version: '3.8'

services:
  nginx:
    image: my-nginx-https-image
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/nginx-selfsigned.crt:/etc/nginx/certs/nginx-selfsigned.crt
      - ./certs/nginx-selfsigned.key:/etc/nginx/certs/nginx-selfsigned.key